### ISSUE TITLE
error when training

### ISSUE THREAD

**Issue by MaoPopovich** [joytsay/livenessDetection#4]
hello, when I run the training script, an error occurs:
Traceback (most recent call last):
  File "train_liveness.py", line 93, in <module>
    epochs=EPOCHS)
  File "/home/qinghuamao/.conda/envs/faceswap/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/qinghuamao/.conda/envs/faceswap/lib/python3.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/qinghuamao/.conda/envs/faceswap/lib/python3.7/site-packages/keras/engine/training_generator.py", line 144, in fit_generator
    val_x, val_y, val_sample_weight)
  File "/home/qinghuamao/.conda/envs/faceswap/lib/python3.7/site-packages/keras/engine/training.py", line 789, in _standardize_user_data
    exception_prefix='target')
  File "/home/qinghuamao/.conda/envs/faceswap/lib/python3.7/site-packages/keras/engine/training_utils.py", line 138, in standardize_input_data
    str(data_shape))
ValueError: Error when checking target: expected fc2 to have shape (1,) but got array with shape (2,)
I can't figure it out. by the way, what's the version of keras and tf presented in your code?mine is tf-gpu1.15.0 and keras2.2.4

**Comment by MaoPopovich** [comment]
in train_liveness.py line69,"labels = np_utils.to_categorical(labels, 2)" 
I change it to"labels = np_utils.to_categorical(labels,2)", and it worked!

**Comment by MaoPopovich** [comment]
in train_liveness.py, line 69, when I change "labels = np_utils.to_categorical(labels, 2)" to
"labels=np_utils.to_categorical(labels)",  it worked. though maybe there are no differences.

**Comment by joytsay** [comment]
Yes according to the latest keras documentation:
[https://keras.io/api/utils/python_utils/#to_categorical-function](url)

> num_classes: total number of classes. If None, this would be inferred as the (largest number in y) + 1.

Thx for the update!
